### ISSUE TITLE
backward関数について

### ISSUE THREAD

**Issue by yuma-long** [Matsushima-lab/FLSA#7]
flsa_dp.pyを実行すると`backward`の際にbpが無いというエラーが出てしまいます。

```
delta_squared[1]: {'knots': [-0.5, 0.5], 'coef_list': [[1, -1.5], [2, -1], [1, -0.5]]}
Traceback (most recent call last):
  File "flsa_dp.py", line 199, in <module>
    beta = solver(np.array([0,1]), 0.5)
  File "flsa_dp.py", line 194, in solver
    beta[i - 1] = delta_squared[i].backward(next_beta=beta[i])
  File "flsa_dp.py", line 35, in backward
    return max(min(next_beta, self.bp), self.bm)
AttributeError: 'DeltaSquared' object has no attribute 'bp'
```

`forward`を実行していれば必ず`self.bp`に格納されるはずなのですが、なぜでしょうか、、、

**Comment by yuma-long** [comment]
193行目の
```python
beta[i - 1] = delta_squared[i].backward(next_beta=beta[i])
```
について、```delta_squared[i]```のindexをi-1に修正して解決しました。
